# Generated by Django 4.2.1 on 2023-07-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_branch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
