# Generated by Django 4.2.1 on 2023-07-05 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_merge_20230628_0406'),
        ('inventory', '0008_rename_autonomia_car_autonomy_car_rpm'),
    ]

    operations = [
    ]
