# Generated by Django 4.2.1 on 2023-06-26 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_id_article_order_detail_id_replacement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_detail',
            old_name='id_article',
            new_name='id_replacement',
        ),
    ]
