# Generated by Django 4.2.1 on 2023-06-28 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_article_deleted'),
        ('order', '0004_rename_id_article_order_detail_id_replacement'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_detail',
            name='id_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.branch_article'),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='id_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.branch_article'),
        ),
    ]
