# Generated by Django 4.2.1 on 2023-07-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_bill_detail_id_bill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='total',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='bill_detail',
            name='subtotal',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='total',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='quotation_detail',
            name='subtotal',
            field=models.BigIntegerField(),
        ),
    ]
