# Generated by Django 4.2.1 on 2023-07-05 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_bill_id_customer_alter_bill_id_employee_and_more'),
        ('order', '0007_alter_bill_detail_id_bill_and_more'),
        ('order', '0007_alter_bill_total_alter_bill_detail_subtotal_and_more'),
    ]

    operations = [
    ]
